#!/bin/bash

# WARING, this needs to be copied manually to server
# scp deploy/post-receive aMaze:aMaze.git/hooks/post-receive

TARGET="/home/lukas/aMaze"
GIT_DIR="/home/lukas/aMaze.git"
BRANCH="master"

while read oldrev newrev ref
do
        # only checking out the master (or whatever branch you would like to deploy)
        if [ "$ref" = "refs/heads/$BRANCH" ];
        then
                echo "Ref $ref received. Deploying ${BRANCH} branch to production..."
                git --work-tree=$TARGET --git-dir=$GIT_DIR checkout -f $BRANCH
                # Install dependencies
                $TARGET/venv/bin/pip install -r $TARGET/requirements.txt
                # Migrate and collect static files
                $TARGET/venv/bin/python $TARGET/manage.py migrate
                $TARGET/venv/bin/python $TARGET/manage.py collectstatic --no-input
                # Reload apache
                sudo /usr/bin/systemctl reload apache2.service
        else
                echo "Ref $ref received. Doing nothing: only the ${BRANCH} branch may be deployed on this server."
        fi
done
