# Generated by Django 3.1.7 on 2021-03-19 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_together', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.AlterField(
            model_name='console',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
