# Generated by Django 3.1.7 on 2021-03-19 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play_together', '0004_auto_20210319_1954'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayerGameConsoleRelation',
            new_name='OwnedGames',
        ),
    ]
