# Generated by Django 3.1.7 on 2021-03-20 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("play_together", "0008_auto_20210320_1121"),
    ]

    operations = [
        migrations.AlterField(
            model_name="playergroup",
            name="watched_games",
            field=models.ManyToManyField(blank=True, to="play_together.Game"),
        ),
    ]
