# Generated by Django 3.1.7 on 2021-03-20 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_together', '0009_auto_20210320_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='my_consoles',
            field=models.ManyToManyField(blank=True, to='play_together.Console'),
        ),
    ]
