# Generated by Django 3.1.7 on 2021-03-20 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_together', '0010_player_my_consoles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ownedgames',
            options={'verbose_name': 'Owned Game', 'verbose_name_plural': 'Owned Games Plural'},
        ),
        migrations.AlterModelOptions(
            name='playergroup',
            options={'verbose_name': 'Player Group', 'verbose_name_plural': 'Player Groups'},
        ),
        migrations.AddField(
            model_name='console',
            name='icon',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='comment',
            field=models.TextField(blank=True, help_text='Specify crossplay conditions or any other info', max_length=2000),
        ),
    ]
