# Generated by Django 3.1.7 on 2021-03-20 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_together', '0011_auto_20210320_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='console',
            name='icon',
            field=models.ImageField(upload_to='console-icon/'),
        ),
    ]
