# Generated by Django 3.1.7 on 2021-03-21 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('play_together', '0012_auto_20210320_2156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='my_consoles',
            new_name='consoles',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='my_games',
            new_name='games',
        ),
    ]
