# Generated by Django 3.1.7 on 2021-03-21 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_together', '0013_auto_20210321_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='consoles',
            field=models.ManyToManyField(blank=True, to='play_together.Console', verbose_name='Your Consoles'),
        ),
        migrations.AlterField(
            model_name='player',
            name='games',
            field=models.ManyToManyField(blank=True, through='play_together.OwnedGames', to='play_together.Game', verbose_name='Your Games'),
        ),
    ]
