# Generated by Django 3.1.7 on 2021-03-22 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('play_together', '0014_auto_20210321_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ownedgames',
            name='console',
        ),
        migrations.CreateModel(
            name='OwnedOnConsole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='play_together.console')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='play_together.ownedgames')),
            ],
        ),
    ]
