# Generated by Django 3.1.7 on 2021-03-22 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('play_together', '0016_auto_20210322_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownedgame',
            name='consoles',
            field=models.ManyToManyField(blank=True, to='play_together.Console'),
        ),
        migrations.DeleteModel(
            name='OwnedOnConsole',
        ),
    ]
